### ISSUE TITLE
error when inserting null in varbinary column

### ISSUE THREAD

**Issue by anthonymorel** [microsoft/msphpsql#1097]
## PHP Driver version or file name
pdo_sqlsrv 5.6.1+11919

 ## SQL Server version
 14.0.2027

 ## Client operating system
 windows 10

 ## PHP version
 7.3.13

 ## Table schema
```sql
CREATE TABLE [dbo].[tableName] (
   [Id] int NOT NULL DEFAULT ((0)) ,
   [Doc_Blob] varbinary(MAX) NULL DEFAULT NULL
)
```

 ## Problem description
**When** executing the following code to insert new record with null in the varbinary column:

```php
$sql = "INSERT INTO tableName(Id, Doc_Blob) VALUES (?,?)";
$stmt= $pdo->prepare($sql);
$stmt->execute([1, null]);
```

**Then** the following error occurred 

> [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Implicit conversion from data type char to varbinary(max) is not allowed. Use the CONVERT function to run this query.

 ## Expected behavior and actual behavior
 The same query without parameters works fine

the same query with parameters works also fine in another environment (php 7.2.16 and pdo sql srv 5.4.0-preview)

**Comment by yitam** [comment]
@anthonymorel do note that this is by design, as indicated in [our PDO documentation for binding parameters](https://docs.microsoft.com/sql/connect/php/pdostatement-bindparam?view=sql-server-ver15#remarks)

This should not have worked in previous versions, as you have mentioned. I just double checked it myself:

![image](https://user-images.githubusercontent.com/21340756/74555001-9e782880-4f0f-11ea-8797-f32ac1998068.png)

Perhaps in your other environment, the column is of type `varchar(max)`, not `varbinary(max)`?

> The same query without parameters works fine

Because it is a generic query sent to the server, so no binding necessary. 

To bind a null value to any binary field (varbinary, binary, or varbinary(max)), please do something like this:
```
$v1 = 1;
$v2 = null;
$sql = "INSERT INTO $tableName(Id, Doc_Blob) VALUES (?, ?)";
$stmt = $conn->prepare($sql);
$stmt->bindParam(1, $v1);
$stmt->bindParam(2, $v2, PDO::PARAM_LOB, 0, PDO::SQLSRV_ENCODING_BINARY);
$result = $stmt->execute();
```

You can see the values with SSMS afterwards, like this:

![image](https://user-images.githubusercontent.com/21340756/74555220-2100e800-4f10-11ea-8254-0cc5302bdeb6.png)

**Comment by anthonymorel** [comment]
Hello

Thanks for your reply.
We have try your solution above.
However, we obtain the same error as previously.
Are there any parameters to set ? When opening the connection for example or elsewhere ?
