### ISSUE TITLE
PHP's DateTime type and SQL Server's Date Type mismatch

### ISSUE THREAD

**Issue by timnash** [microsoft/msphpsql#1276]
Hello,

I'm not sure if this is expected behavior or a bug, but this is an issue that I'm having so I thought I would report it to find out.

I'm running SQLSRV 5.9.0 with PHP 8.0 and MSODBCSQL 17.7.2.1-1 on Ubuntu 20.04, accessing SQL Server 15.0.2080.9 Development Edition running on a Windows 10 Pro machine (my dev machine, but we are also having this issue on another SQL Server 12.0.6164.21 Web Edition).

We have a table that stores data in the Date format. I'm trying to run a SELECT query with a WHERE clause that looks for rows with a specific Date, but I'm parameterizing the query with a DateTime object for that date. I would expect for that SELECT query to select the rows with that date, but it instead returns nothing (I expected that it would return since I can run an INSERT parameterized with the DateTime and it works fine. It also throws no errors.)

Here's code to reproduce:
```
<?php
$db = sqlsrv_connect('databaseConnectionString', array(
    "UID" => "databaseAdmin",
    "PWD" => "databaseAdminPassword",
    "CharacterSet" => "UTF-8"
));

$now = new DateTime();

sqlsrv_begin_transaction($db);
sqlsrv_query($db, "CREATE DATABASE testDateBug");
sqlsrv_query($db, "USE testDateBug");
sqlsrv_query($db, "CREATE TABLE testTable (
    testID int IDENTITY PRIMARY KEY,
    testDate date NOT NULL
    )");
sqlsrv_query($db, "INSERT INTO testTable (testDate) VALUES (?)", array($now));
$result = sqlsrv_query($db, "SELECT testID FROM testTable WHERE testDate = ?", array($now->format("Y-m-d")));
$hasRows = sqlsrv_has_rows($result);
echo "Has Rows? " . ($hasRows?"TRUE":"FALSE") . PHP_EOL; //Returns TRUE
$result = sqlsrv_query($db, "SELECT testID FROM testTable WHERE testDate = ?", array($now));
$hasRows = sqlsrv_has_rows($result);
echo "Has Rows? " . ($hasRows?"TRUE":"FALSE") . PHP_EOL; //Returns FALSE...
sqlsrv_rollback($db);
sqlsrv_close($db);
```

**Comment by yitam** [comment]
Hi @timnash , this is by design. The column is of type `Date`, and your first query by specifying the format `$now->format("Y-m-d")` is correct. In this case, your input is a string, and there is no conversion behind the scene, so it's straightforward. 

However, with your second query, since the parameter is passed in as a PHP `DateTime` object, the sqlsrv driver first converts it to a [datetimeoffset](https://docs.microsoft.com/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver15) and then to a string such that no details will be missed. 

With no timezone specified, UTC is the default, so the second SQL statement is essentially equivalent to the one shown below, which explains why no row is matched:
`SELECT testID FROM testTable WHERE testDate = "2021-07-05 16:58:40.543746 +00:00"`

The reason why insertion works is that the input object is converted to `Date` type during insertion.

That being said, with the sqlsrv driver, there is a way to indicate the data type of [your input parameter](https://docs.microsoft.com/sql/connect/php/sqlsrv-query?view=sql-server-ver15): 
`array($value [, $direction [, $phpType [, $sqlType]]])`

Hence, you need to change your php script like this:

```
$param = array(array($now, null, null, SQLSRV_SQLTYPE_DATE));
$result = sqlsrv_query($db, "SELECT testID FROM testTable WHERE testDate = ?", $param);
$hasRows = sqlsrv_has_rows($result);
echo "Has Rows? " . ($hasRows?"TRUE":"FALSE") . PHP_EOL; 
```

Please give it a try. Hope this clarifies things.

**Comment by timnash** [comment]
Thank you, that's a very comprehensive answer.
