### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so'

### ISSUE THREAD

**Issue by Kat35601** [microsoft/msphpsql#1399]
PHP 8.1.7 (cli) (built: Jun 25 2022 08:12:59) (NTS) 

Not sure the version. I ran 
sudo pecl install sqlsrv
sudo pecl install pdo_sqlsrv

Instructions from "https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16"

Linux Mint 20.3

Error
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20210902/sqlsrv.so (/usr/lib/php/20210902/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/sqlsrv.so.so (/usr/lib/php/20210902/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20210902/pdo_sqlsrv.so (/usr/lib/php/20210902/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/pdo_sqlsrv.so.so (/usr/lib/php/20210902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.7 (cli) (built: Jun 25 2022 08:12:59) (NTS)

 /etc/php/8.1/mods-available/sqlsrv.ini 
; priority=20
extension=sqlsrv.so

/etc/php/8.1/mods-available/pdo_sqlsrv.ini
; priority=30
extension=pdo_sqlsrv.so

neither file sqlsrv.so or pdo_sqlsrv.so on on my computer anyware.

I have attempted to remove and reinstall

**Comment by absci** [comment]
Hi, we don't officially support Linux Mint. Here's the [Support Matrix](https://docs.microsoft.com/en-us/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver16#supported-operating-systems).

**Comment by Fodba** [comment]
I have the same issue on windows 10 for the same files with .dll extension
![ticket_sqlsrv_cmd](https://user-images.githubusercontent.com/5937602/195589349-03d84a84-29e1-4755-b247-6086933c22f5.PNG)

Here is my  php.ini (in the php folder): 
![ticket_sqlsrv_phpini](https://user-images.githubusercontent.com/5937602/195589358-4a87cf43-4cff-4f4b-8a20-3a82d2ffa4d2.PNG)
and the dll files are located in the ext/ folder of PHP.

It's just a warning, not an error but when I try to connect to my SQL Server database using symfony, I got this:
![ticket_sqlsrv_symfony_cmd](https://user-images.githubusercontent.com/5937602/195599365-9d1c8a89-8632-4f3b-b6ba-26324c8705c4.PNG)

I'm getting mad because I can't understand the issue and all the people who have solved this problem seems to just have put the files in ext/ folder, change their php.ini file.

**Comment by Fodba** [comment]
I don't know how or why but the warning no longer appears. I didn't do anything.
If you have any explanations, I would like to know.

![ticket_sqlsrv_cmd2](https://user-images.githubusercontent.com/5937602/197485148-1a006dd2-f30a-4300-8785-3a6ea1a2ffa8.PNG)

Now I have a new message is about sqlsrv_configure. But I'm going to look around for a solution.
Thanks and sorry for your time.
