### ISSUE TITLE
SQL server connection

### ISSUE THREAD

**Issue by RameshSubramaniL** [Microsoft/msphpsql#1509]
Microsoft ODBC Driver 17 for SQL Server : SSL Provider: [error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol].
 Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.
  
  i get this ODBC driver error when i try to connect sql server ,i tried update version of ODBC and then below code changes 

  [default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1 

i get same error whatever i change ,any solution for fix this error?

**Comment by v-makouz** [comment]
You can try setting MinProtocol to `TLSv1.0` and CipherString to `DEFAULT@SECLEVEL=0`, but the best approach is to patch the server to support TLS 1.2

**Comment by d4em0nsp4wn** [comment]
I am having a similar issue, sqlcmd, isql, and even setting up the connection in PHP  using "new PDO('odbc:Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.3.1;...connection string here);" works....but sqlsrv_connect fails with  "Client unable to establish connection because an error was encountered during handshakes before login. Common causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maximum allowed connections) on the server."   code 26, sqlstate 08001;    code 10054, [Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: Error code 0x2746.  A tcp dump shows proper TLSv1.2 handling with all tools mentioned above, however, a tcp dump with sqlsrv_connect shows only 8 packets before the connection is interrupted.   The PHP environment is PHP 8.0.30. The same occurs regardless of using PHP 7.4 to 8.3.  Also worth nothing the TCP dump shows the source and destination ports to be the same for every packet, whereas PDO, isql, and sqlcmd all have a randomized starting port.  The sql instance is using a custom tcp port.  The sql server requires TLS 1.2, and is SQL Server 2016.

**Comment by v-makouz** [comment]
Which operating system is this one?

**Comment by d4em0nsp4wn** [comment]
> Which operating system is this one?

Cloudlinux/AlmaLinux 8. 64bit.

**Comment by v-makouz** [comment]
Does it give the same error when using only ODBC (isql, sqlcmd)? Or is it specific to PHP driver?

**Comment by d4em0nsp4wn** [comment]
> Does it give the same error when using only ODBC (isql, sqlcmd)? Or is it specific to PHP driver?

The error is only specific when using the sqlsrv.so native module within PHP, isql, sqlcmd, and $pd = new PDO('odbc:Driver=/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.3.1;SERVER= dsn works just fine within PHP, but we are unable to use the PDO driver in this manner as the odbc function to permit multiple active results sets does not appear to work within PDO. 
We specified both version 18 and version 17 and got the same errors out of the msphpsql modules.

**Comment by absci** [comment]
Hi, Cloudlinux/AlmaLinux is not one of our supported platforms, is it possible for you to use other systems? The support matrix is [here](https://learn.microsoft.com/en-us/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver16#supported-operating-systems).

**Comment by d4em0nsp4wn** [comment]
> Hi, Cloudlinux/AlmaLinux is not one of our supported platforms, is it possible for you to use other systems? The support matrix is [here](https://learn.microsoft.com/en-us/sql/connect/php/microsoft-php-drivers-for-sql-server-support-matrix?view=sql-server-ver16#supported-operating-systems).

It is not possible.  I am curious what might be missing from this platform since it is a RHEL Clone.

**Comment by v-makouz** [comment]
This is not a PHP driver issue, but rather compatibility between OpenSSL and SQL Server. Starting with OpenSSL 3.0 TLSv1.0 and TLSv1.1 were deprecated and are not allowed by default, requiring at least TLSv1.2. Many older servers don't have TLSv1.2, thus the connection fails. The ideal solution is to patch or upgrade the server. If that's not possible, one can configure OpenSSL to still allow use of older protocols, but it's best to consult OpenSSL documentation or support for the most up to date instructions for how to do so.
