### ISSUE TITLE
SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:0A0C0103:SSL routines::internal error]

### ISSUE THREAD

**Issue by 0neCigarettes** [Microsoft/msphpsql#1513]
please help me for this issue
I use ubuntu 22.04, php 7.4

**Comment by v-makouz** [comment]
This sounds like an issue with an SQL Server that's too old. What's the version on the server?

**Comment by 0neCigarettes** [comment]
> This sounds like an issue with an SQL Server that's too old. What's the version on the server?

installed Microsoft SQL Server 2012 - 11.0.2100.60 (X64)

**Comment by v-makouz** [comment]
This does look like a fairly old version, that I believe might be out of support. Are there other servers to try? The issue is that modern OSs have higher security requirements than are available on those old servers. So the solutions usually are: use newer server, patch the old server with the latest service pack, or lower the security settings on the client.

So ideally if you have or can create other test VMs with newest SQL Servers on one it would be great to test if this is indeed the solution.

**Comment by 0neCigarettes** [comment]
thank's for your help, I have downgrad Ubuntu vm to 20.04 and also the security settings on the client to lowered version, now I can connect to the sqlserver

**Comment by Kitsunejasutin** [comment]
> thank's for your help, I have downgrad Ubuntu vm to 20.04 and also the security settings on the client to lowered version, now I can connect to the sqlserver

` also the security settings on the client to lowered version`  How did you this? I can't seem to configure my php docker image to run on lowered version as I can't update the SQL Server at the moment

edit: I used TLSv1.0 and it works now, man. This server is ancient
