### ISSUE TITLE
Support "decimal" and "numeric" data types with SQLSRV_ATTR_FETCHES_NUMERIC_TYPE

### ISSUE THREAD

**Issue by zax123** [Microsoft/msphpsql#291]
Hi,

I was wondering if you were planning to add support for the "decimal" and "numeric" data types in pdo_sqlsrv such that a query will return a PHP double data type the way a float would.  I have a lot of databases using the decimal(14, 2) or numeric(14, 2) (for ex.) data types for storing currency information and some of them I cannot change.

Please let me know if this is something you intend on supporting in the near future.

Thank you!

Robert

**Comment by zax123** [comment]
I forgot to mention that right now (on the current version), even with the SQLSRV_ATTR_FETCHES_NUMERIC_TYPE attribute set to true, decimal and numeric data types return a "string" data type in PHP whilst a float data types will return a "double" data type in PHP.

**Comment by yitam** [comment]
@zax123 we will get back to you on this. Please stay tuned.

**Comment by zax123** [comment]
Thanks, Jenny!  I look forward to hearing from you.

**Comment by zax123** [comment]
Hi Jenny,

Just wondering if you had any news for me?  I woud like to give my employer some idea of when this might be supported, or if I should start working on code to handle this another way as we have a time-sensitive system that depends on it.

Thank you!

Robert

**Comment by yitam** [comment]
@zax123 We are looking into doing this. We don't have an ETA yet. Stay tuned. Thanks, Robert.

**Comment by v-kaywon** [comment]
Hi @zax123,

After some investigation in the PHP float type, we do not think it's a good idea to return sql decimal and numeric types to float, since float cannot represent 0.1 (or any other negative power of ten) exactly. In your case specifically, working with currency information requires precision, and float type cannot give you that. As you perform more operations on inexact numbers, you'll lose more and more precision.

Furthermore, if you perform PHP arithmetic operations on stringified numbers, PHP implicitly cast it to float and then perform the operation. PHP extensions that are designed to operate on numbers (such as the Decimal extension or the BCMath library) also accept stringified numbers for their functions. I'm guessing the primary reason you want decimals to be represented as float is to pass the numbers to a database or some other programming environment. If that is the case, you can easily convert it to float using floatval($var).

Hope that helps, thank you.

**Comment by Hadis-Fard** [comment]
Nice

**Comment by zax123** [comment]
Hi v-kaywon,

Thank you for the reply.  The problem I'm having is when returning stringified numbers and then passing them to json (asked for by a js ajax call), the javascript continues to treat them as strings.  I understand that I can cast them to float, but I have a big programming project that I have to convert from an old PHP DB abstraction layer (PEAR DB) to PDO and I was able to make wrappers for the PEAR DB functions.  But the code fails at this point.  Could we not add an option perhaps to the query functions to add a rounding parameter or something?  The data is sound in the MS SQL database, so there must be a way to convert it to float without losing precision...

Please let me know, it would save me hours and hours of time.  Thank you!

Robert

**Comment by v-kaywon** [comment]
Hello @zax123,

Unfortunate, our PDO driver needs to follow the specification outlined in the PHP PDO documentation (http://php.net/manual/en/pdo.query.php) thus we cannot add an option (not just pdo::query, but all PDO APIs). Furthermore, with a rounding parameter, although the number may seem to be rounded off and looks precise, but as long as the number is a float, it cannot be exact.

We understand your struggle, however, converting SQL decimal and numeric types to PHP float types may affect a lot of other users, thus we cannot make this change.

Thank you,

Yuki

**Comment by zax123** [comment]
Hi Yuki,

I totally understand that you can't change this for everyone as it would affect current users.  Can I maybe suggest one last thing?

You guys have a bunch of constants (eg. PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE) which define the behavior of the PDO driver and is dependent on using the PDO_SQLSRV driver specifically.  Would you consider a new attribute such as PDO::SQLSRV_ATTR_FETCH_FLOAT_AND_NUMERIC_AS_NUMBER or something along those lines where the default behavior would be to retrieve floats and numeric as a string but if you set that attribute, it retrieves them as a php float?

I'm sorry to keep pushing.  I'm just wondering if you would consider that.

Thank you!

Robert

**Comment by v-kaywon** [comment]
Hi Robert,

We have considered this alternative. However, since we want to match the functionalities in our PDO_SQLSRV and SQLSRV drivers, and SQLSRV does not have PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE, we've decided to not to implement this.

One solution for you is to get our PDO_SQLSRV source code and modify it for your own use and build our drivers from source (see instruction in https://github.com/Microsoft/msphpsql/blob/master/README.md). The lines that you'll need to modify to fetch float when PDO::SQLSRV_ATTR_FETCHES_NUMERIC_TYPE is turned on is pdo_stmt.cpp (1322-1336):

`case SQL_FLOAT:
        case SQL_REAL:
            if ( this->fetch_numeric ) {
                sqlsrv_phptype.typeinfo.type = SQLSRV_PHPTYPE_FLOAT;
            }
            else {
                sqlsrv_phptype.typeinfo.type = SQLSRV_PHPTYPE_STRING;
                sqlsrv_phptype.typeinfo.encoding = local_encoding;
            }
            break;
        case SQL_BIGINT:
        case SQL_CHAR:
		case SQL_DECIMAL:
        case SQL_GUID:
		case SQL_NUMERIC:`

You can simply move the switch cases SQL_DECIMAL and SQL_NUMERIC up to do the same thing as SQL_FLOAT and SQL_REAL.

I hop that will solve your problem. Thank you,

Yuki

**Comment by zax123** [comment]
Hi Yuki,

Thank you, that might work for me!

I see that there are build instructions for Windows.  I am using this on Linux (Ubuntu 16).  Do you have build instructions for Linux somewhere?  Please let me, thank you!

I appreciate all the help.

Robert

**Comment by v-kaywon** [comment]
Hi Robert, please follow these steps (this assumes you already have php):

1. Download our source code and make you changes with the decimal and numeric switch cases
2. cd to the `source `directory and run `./packagize`
3. cd to the `pdo_sqlsrv `directory (now you should see the shared folder is there) and run the following:
```
    - phpize
    - ./configure
    - make
    - sudo make install
```
Now you should be able to see `pdo_sqlsrv.so` in the extension folder in php

**Comment by zax123** [comment]
Hi Yuki,

I actually figured out before your message, but thank you. :)

I made the change, compiled and installed the new .so and it's working perfectly!

Thanks for the suggestion!

Robert

**Comment by v-kaywon** [comment]
Glad I could help. :)
