### ISSUE TITLE
Output param is incorrectly bound when the inputs are decimals

### ISSUE THREAD

**Issue by yitam** [Microsoft/msphpsql#321]
Discovered this issue while running a simple PDO script as follows:

```
$procName = "tempProcTest";
$stmt = $conn->exec("CREATE PROC $procName (@p1 DECIMAL, @p2 DECIMAL, @p3 CHAR(128) OUTPUT) 
AS BEGIN SELECT @p3 = CONVERT(CHAR(128), @p1 + @p2) END");
                                       
$inValue1 = 2.1;  // or '2.1'
$inValue2 = 5.3;  // or '5.3'
$outValue = 0;    // or '0'
                        
$stmt = $conn->prepare("{CALL $procName (?, ?, ?)}");
$stmt->bindValue(1, $inValue1);
$stmt->bindValue(2, $inValue2);
$stmt->bindParam(3, $outValue, PDO::PARAM_STR, 5);
$stmt->execute();
$stmt->closeCursor(); // with or without this doesn't make a difference
var_dump($outValue);
```

The output is 
```string(5) "7    "```

Same problem with sqlsrv as well: 
```
$params = array(
                array($inValue1, SQLSRV_PARAM_IN), 
                array($inValue2, SQLSRV_PARAM_IN), 
                array(&$outValue, SQLSRV_PARAM_OUT, SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_CHAR))
                );
$stmt = sqlsrv_prepare($conn, "{CALL $procName (?, ?, ?)}", $params);
sqlsrv_execute($stmt);
```

Suspect that it might have something to do with the call to convert_input_param_to_utf16(). While debugging, one of input values 2.1 is converted to 2, etc.

**Comment by v-kaywon** [comment]
This is because when the input parameters are declared in the stored procedure, the type is indicated as `DECIMAL`. When no precision and scale are provided to the `DECIMAL` type, the default precision and scale are `18` and `0` respectively, and with a scale of 0, a decimal number is rounded off to an integer. In the above example, if you want to retrieve `"7.4"` instead of `"7"`, all you have to do is to set the scale in the input parameters when you create the stored procedure:
`$stmt = $conn->exec("CREATE PROC $procName (@p1 DECIMAL(18,1), @p2 DECIMAL(18,1), @p3 CHAR(128) OUTPUT) 
AS BEGIN SELECT @p3 = CONVERT(CHAR(128), @p1 + @p2) END");`

**Comment by Hadis-Fard** [comment]
+1 Could you also add a test for this scenario?
