### ISSUE TITLE
Unexpected result for sqlsrv_num_rows

### ISSUE THREAD

**Issue by jansor** [Microsoft/msphpsql#330]
Hi, I am not sure is this is a bug or the behavior is correct but when i execute below code the web server crashes. It provides me with Bad Gateway 

The original script that i used was much bigger but when i execute this test script i got the same issue:
`<?php
$server = "localhost";
$connectionInfo = ["UID" => "localhost", "PWD" => "localhost", 'Database' => 'localhost'];
$conn = sqlsrv_connect($server, $connectionInfo);

$stmt = sqlsrv_query($conn, "IF EXISTS (SELECT * FROM [sys].[objects] WHERE (name LIKE 'tbl_Test%') AND type in (N'U'))
                BEGIN
                    select 0
                END", [], ['Scrollable' => SQLSRV_CURSOR_CLIENT_BUFFERED]);

if ($stmt) {
    $hasRows = sqlsrv_has_rows($stmt);
    $numRows = sqlsrv_num_rows($stmt);
    var_dump($hasRows, $numRows);
}
?>`

Following scenario is expexted, when the table name like tbl_Test exists it would return the amount of tables that are found, hens sqlsrv_has_rows would be true and sqlsrv_num_rows would return the amount
When no tables are found sqlsrv_has_rows must be false, sqlsrv_num_rows would be zero. 

Thanks to look into this

PS i am using following setup
IIS10, PHP7.1.2  and SQL Driver 4.1.7-preview on an SQL 2016 server

**Comment by v-kaywon** [comment]
Hello @jansor, we are able to reproduce the issue. Thank you for reporting to us.

The behavior that you expect when table name like 'tbl_Test%' exists is incorrect. For example, say you have three tables 'tbl_Test1', 'tbl_Test2' and 'tbl_Test3'. The query you have will return 0 due to the `select 0`. Thus `sqlsrv_num_rows` will return `1` and not `3` as you have expected. If you want to count the number of tables with name like 'tbl_Test%', you can try the following query:
`SELECT COUNT(*) from sys.objects where (name LIKE 'tbl_Test%') AND (type = 'U')`

**Comment by jansor** [comment]
Yes you are correct, in my testing previous i had the select query from the if statement also inside the select 0 statement. Thanks for the confirmation its a bug, i was confused with the result set.

**Comment by v-kaywon** [comment]
One thing to note on the behavior of `sqlsrv_num_row`. If the result set is empty it should return `0` (for example, "SELECT * FROM TABLE1" and TABLE1 is empty). If the result set is null it should return `-1` (for example, "CREATE TABLE TABLE1 (c1 int)" in which the query is not meant to return any result set).

Using your example, if there is no table like 'tbl_Test%', only
`IF EXISTS (SELECT * FROM [sys].[objects] WHERE (name LIKE 'tbl_Test%') AND type in (N'U'))`
is executed and this query is not meant to return a result set, so the return value of `sqlsrv_num_row `would be `-1`.

The bug is currently being investigated, please stay tune.

**Comment by v-kaywon** [comment]
The fix should be in the latest release (4.1.8-preview). Please check to see if your problem still exist.
