### ISSUE TITLE
sqlsrv_errors, error message returns some driver version

### ISSUE THREAD

**Issue by genyslt** [Microsoft/msphpsql#414]
Hello,

## Issue

When i try to get error message (for example: raiserror on trigger) i get message with driver version included:

```
$errors = sqlsrv_errors();
print_r($errors);
die();
```

the result is:

```
Array
(
    [0] => Array
        (
            [0] => 42000
            [SQLSTATE] => 42000
            [1] => 50000
            [code] => 50000
            [2] => [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]My Error Text
            [message] => [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]My Error Text
        )
)
```
## Question

1. **[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]** - Why this going on message?
2. Why i get the same information 0 AND SQLSTATE, 1 AND CODE...

## System info

**PHP version:** 7.1.5
**Linux version:** Ubuntu 16.04.2 LTS
**sqlsrv_client_info:**
[DriverName] => libmsodbcsql-13.1.so.8.0
[DriverODBCVer] => 03.52
[DriverVer] => 13.01.0008
[ExtensionVer] => 4.0.8.0
**sqlsrv_server_info:**
[SQLServerVersion] => 12.00.2000

**Comment by v-kaywon** [comment]
@genyslt ,

[Microsoft][ODBC Driver 13 for SQL Server][SQL Server] means the error comes from the ODBC driver. (for instance, if you try to bind binary data but your encoding is utf-8, the ODBC will complain about conversion problems. The SQLSRV driver passes the binary data and the encoding to the ODBC driver but does not check whether the conversion is valid).

The message shown in [0] and [SQLSTATE] are the same. It is designed this way so the user can access the information using a numeric key or a associative key.

**Comment by genyslt** [comment]
Why this ODBC complain about conversion problems written on message key? The message must be original message from SQL Server. Any complaints can go to other key?

**Comment by v-kaywon** [comment]
@genyslt,
The SQLSRV driver is a wrapper around the Microsoft ODBC driver. You can see [here](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/appendix-a-odbc-error-codes) for a list of possible errors from the Microsoft ODBC driver. The message doesn't have to be the original message from the SQL Server because the error could come from the SQL Server, the Microsoft ODBC Driver, or the PHP SQLSRV Driver. Please see [here](https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-errors) for the return values of sqlsrv_error().

**Comment by jacekk015** [comment]
An because of that message that contains driver version etc. you can't use RAISERROR or THROW inside your Stored Procedure to return an error back to APP.
Instead you need to use some SELECT or OUTPUT parameter to forward your message back to APP.
Did someone was thinking about that we can't use a proper error handling because of that?
My customer doesn't need to know ODBC version when I use:
`;THROW 50000, @errormsg, 1;`
