### ISSUE TITLE
Low performance on Ubuntu 16.04

### ISSUE THREAD

**Issue by okmkey45** [Microsoft/msphpsql#422]
Hi

I am having a really low performance on ubuntu and I would like to know why. I have a task running on windows that takes about 20 or 30 minutes to finisg, but running on Ubuntu, the task might take between 6 or 8 hours. This is really worrying. I read in this [performance issue](https://github.com/Microsoft/msphpsql/issues/189) that some improvements will be made. So, I hope you can help to figure this out because the difference is really huge.

Thanks.

**Comment by meet-bhagdev** [comment]
@okmkey45 Do you have a repro script and a sample schema that we can take a look at?

**Comment by meet-bhagdev** [comment]
@okmkey45 ping. do you have a repro script?

**Comment by ulvii** [comment]
Hi @okmkey45 ,

I ran a few scripts on both Ubuntu and Windows machines in our test lab and could not really observe that huge of a difference. It is highly unlikely that you are running into performance issues because of SQLSRV drivers. I am closing the issue, please feel free to re-open it if you can provide a repro script for us to investigate.
