### ISSUE TITLE
PHP 7.2 roadmap?

### ISSUE THREAD

**Issue by brainfoolong** [Microsoft/msphpsql#444]
Just asking for the timeline of PHP 7.2 support? First alpha is already released and we are already do internal tests with it.

**Comment by meet-bhagdev** [comment]
@brainfoolong We are working on this. I will use this issue to give an ETA and roadmap for PHP 7.2

**Comment by MCF** [comment]
FWIW PHP 7.0 and 7.1 have memory corruption problems that occasionally crop up.  In my experience the problems seems to be more prevalent on Windows then *nix operating systems.  There is no real workaround on PHP 7.0 and 7.1.  The problem seems to have been (mostly?) addressed in PHP 7.2.  So it may be that PHP users on Windows are more motivated than usual to upgrade to PHP 7.2 because of this.

Some more information about this is availiable at these links:

https://bugs.php.net/bug.php?id=74833
https://github.com/cakephp/chronos/issues/147

**Comment by MCF** [comment]
And I've been running a PHP 7.2 build of the PDO MS driver (4.3.0 RC-1) with no problems for the last week.  So hopefully it is not a big deal to provide 7.2 builds of the drivers soon (First PHP7.2 beta drops in about 10 days).

**Comment by Hadis-Fard** [comment]
@MCF hapy to hear that you didn't face a major issue!  we're gonna support PHP 7.2 in our next previews. please stay tuned

**Comment by theodorejb** [comment]
v5.0.0 preview was released and the changelog says PHP 7.2 Beta 1 is supported, but I don't see any way to download Windows DLLs for PHP 7.2. Was this overlooked?

**Comment by meet-bhagdev** [comment]
We will be uploading them on GitHub releases ASAP. in the meanwhile @Hadis-Fard can point you to the DLL's on PECL

**Comment by MCF** [comment]
Thanks for the 7.2 Windows builds.  I've been running the new drivers with PHP 7.2 beta2 (dropped this morning).  Everything is working fine.

**Comment by brainfoolong** [comment]
Tested here with PHP 7.2 beta2, Windows 10 64bit. Works fine for our requirements. (Insert, Update, Select)

**Comment by MCF** [comment]
Looks like the windows builds of the latest (5.1) packages are not available for PHP 7.2 anywhere.  Any possibility of having them built and uploaded to github?

**Comment by meet-bhagdev** [comment]
@MCF We will be uploading them soon. We need to get the windows binaries signed and there is an outage causing the delay. Stay tuned :)

**Comment by yitam** [comment]
Closing this as we already have binaries up for PHP 7.2

**Comment by theodorejb** [comment]
Where can I find the v5.1.2 Windows binaries for PHP 7.2?
