### ISSUE TITLE
Error returning unaliased constants from query in associative mode

### ISSUE THREAD

**Issue by mnewnham** [Microsoft/msphpsql#62]
A Query is constructed: 

``` php
SELECT 'test', null, 'this is another element'
```

When executed  and the result set retrieved like this

``` php
sqlsrv_fetch_array($queryId,SQLSRV_FETCH_NUMERIC)
```

The result is:
[0] => 'test',
[1] => ,
[2]=> 'This is another element'

When executed  and the result set retrieved like this

``` php
sqlsrv_fetch_array($queryId,SQLSRV_FETCH_ASSOC)
```

The result is:
[] => 'This is another element'

The driver is not assigning a name to a column if there is none, so each array element overwrites the previous. If each column is assigned an alias:

``` php
SELECT 'test' col1, null col2, 'this is another element' col3
```

The result is:
[col1] => 'test',
[col2] => ,
[col3]=> 'This is another element'

As background, the oracle driver returns the same query elements like this:

['test'] => 'test',
[null] => ,
['thisisanothelement']=> 'This is another element'

**Comment by yitam** [comment]
@mnewnham we decided not to change the existing behavior of how sqlsrv_fetch_array() works with SQLSRV_FETCH_ASSOC mode because there is a workaround as you have shown. 

The reasons behind our decisions are twofold. First, t's clearly written in [documentation](http://php.net/manual/en/function.sqlsrv-fetch-array.php) that 

> A fetch type of SQLSRV_FETCH_ASSOC should not be used when consuming a result set with multiple columns of the same name.

Similarly, in the official [guide](https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-fetch-array) it indicates that
>If a column with no name is returned, the associative key for the array element will be an empty string (""). 

Besides, it's possible your suggestion would break some valid assumptions in the existing code.

Therefore, we will close this issue. Please feel free to re-open.
