### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by zhiephie** [Microsoft/msphpsql#622]
- Sql Sever version: 2008 and 2012
- Client operating system: Ubuntu 17.04
- PHP version: 7.1
- Odbc Driver version: 4.3.0

I have code like this, but the error for trying (example):
1. `http://172.0.0.1/api.php?ext=1001&call_id=0213411` this is work
2. `http://172.0.0.1/api.php?ext=5000&call_id=0213411` this is not worked, and display `Error information`

```
<?php
$serverName = "172.0.0.1";
$connectionOptions = array(
    "Database" => "sampledb",
    "Uid" => "sample",
    "PWD" => "sample"
);
//Establishes the connection
$conn = sqlsrv_connect($serverName, $connectionOptions);
if ($conn) {
   echo "Connected!";
} else {
   die(FormatErrors(sqlsrv_errors()));
}

if (isset($_GET['ext']) && isset($_GET['call_id'])) { 
    //Update Query
    $ext = $_GET['ext'];
    $call_id = $_GET['call_id'];

    $tsql = "UPDATE TBL_LIST_EXT SET CALLER_ID = ? WHERE EXTENSION_ID = ?";
    $params = array($call_id, $ext);
    $getResults= sqlsrv_query($conn, $tsql, $params);
    $rowsAffected = sqlsrv_rows_affected($getResults);
    if ($getResults == FALSE or $rowsAffected == FALSE)
        die(FormatErrors(sqlsrv_errors()));
    echo ($rowsAffected. " row(s) updated: " . PHP_EOL);
    sqlsrv_free_stmt($getResults);
} else {
    $msg = array(
        'msg' => 'Param is empty.'
    );
    echo json_encode($msg);
}

function FormatErrors($errors)
{
    /* Display errors. */
    echo "Error information: ";

    foreach ($errors as $error)
    {
        echo "SQLSTATE: ".$error['SQLSTATE']."";
        echo "Code: ".$error['code']."";
        echo "Message: ".$error['message']."";
    }
}
```

**Comment by david-puglielli** [comment]
Hi @zhiephie could you give us the full error message? Or do you only get `Error information: ` as output?

**Comment by zhiephie** [comment]
Yes, the error output only `Error information:`

**Comment by david-puglielli** [comment]
I think the problem is the use of `==` instead of `===` in `if ($getResults == FALSE or $rowsAffected == FALSE)`. The `==` does type conversion, which means that if `$rowsAffected` is 0, `$rowsAffected == FALSE` returns true. But this is a problem because `sqlsrv_rows_affected` can return 0 (zero) to indicate no rows, or `false` if an error has occurred. These return values have different meanings. So if your query is good and simply returns no rows when `$ext` is 5000, `sqlsrv_rows_affected` returns 0 rather than false, and everything should be fine - but the process dies because the `if` branch is triggered, and `sqlsrv_errors` shows nothing because there are no errors. Changing the `if` condition to `if ($getResults === FALSE or $rowsAffected === FALSE)` should solve the problem, as the `===` does not do type conversion.

For more info on `sqlsrv_rows_affected`, see [here](https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-rows-affected).

**Comment by zhiephie** [comment]
Thank @david-puglielli, trying soon
