### ISSUE TITLE
Randomly occurring Chinese characters in the data

### ISSUE THREAD

**Issue by rapemer** [Microsoft/msphpsql#654]
## Driver version or file name
pdo_sqlsrv 4.3.0 [(php.ini)](https://prnt.sc/hv5s2o)

## SQL Server version
Microsoft SQL Server 2014 (SP2-GDR) (KB4019093) - 12.0.5207.0 (X64) 
        Jul  3 2017 02:25:44 
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

## Client operating system
Debian GNU/Linux 8 (jessie)
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

## PHP version
PHP 7.0.11-1~ dotdeb+8.1 (cli) ( NTS ) 
Copyright (c) 1997-2016 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.11-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

## Microsoft ODBC Driver version
`odbcinst --version`: unixODBC 2.3.1
`sqlcmd -?`: Microsoft (R) SQL Server Command Line Tool Version 13.0.0000.0 Linux
`bcp -v`: BCP - Bulk Copy Program for Microsoft SQL Server. Version: 13.0.0000.0

## Table schema
https://gist.github.com/rapemer/13ca09ee637c69207e196cfe180366e6

## Problem description
When saving data to MSSQL, the Chinese characters are randomly stored at the end of the string (see: https://ctrlv.cz/YfEQ).
The data that is inserted does not include these characters, of course. However, this behavior does not occur in synchronous processes, but only if processes are asynchronous = this means that multiple threads of PHP processes run at once.

Processes as such are controlled via Supervisord, which has several "consumer" (listening to RabbitMQ queues). 1 consumer is not causing problems. 2 consumers who work with the same table in the full load of the database will begin to behave like was reported.

Code of test-case:
	- https://gist.github.com/rapemer/3a12b2fb48b4ce64ef3eef23df62a322
	- in 1 synchronous thread does not cause any problems 
	- at full load (2 and more asynchronous threads) there is an accidental occurrence of errors - it does not always happen
	- charset of PHP application and driver: UTF-8
	- charset of MSSQL database: Czech_CI_CS (this comes from ERP system Helios Orange)

## Expected behavior and actual behavior
In table "product_description" and columns "BaseInfo"+"DetailInfo" should not be any Chinese or uncompatible characters. When trying select this broken data, there should be better error message.

## Repro code
sorry, but I cannot reproduce this behavior because it occurs very randomly :-(

**Comment by v-kaywon** [comment]
@rapemer ,

We have actually fixed a few data corruption bugs since pdo_sqlsrv 4.3.0. Would you mind trying our [latest release](https://github.com/Microsoft/msphpsql/releases/tag/v5.2.0-RC) to see if the problem persists? Meanwhile, I will try to set up Supervisor on my environment to see if I can reproduce the problem. I plan to follow [this link](https://daredevel.com/2013/06/php-jobs-with-gearman-and-supervisor/) to set up Supervisor, please let me know if you think this is a right/wrong approach.

Thank you

**Comment by rapemer** [comment]
@v-kaywon 

of course, we will try to upgrage to the latest stable version and I will report results ASAP. Thanks for your help.

**Comment by rapemer** [comment]
@v-kaywon 
I think you don't need "Gearman", but only "Supervisord". I recommend native documentation: http://supervisord.org/installing.html

then you can run multiple threads of PHP scripts only from Supervisord.

**Comment by v-kaywon** [comment]
@rapemer 
Yes I realized. Gearman isn't even available for PHP7 :( Thanks for your update.

**Comment by v-kaywon** [comment]
@rapemer 

I got supervisor setup in my environment, but I failed to see the problem that you've encountered. You mentioned the problem is intermittent so I tried to run it 10 times but still failed to reproduce it. One reason I can think of could be I was testing with just inserting English into the nvarchar(max) columns. Would you mind sharing the data you have in the BaseInfo and DetailInfo columns?

Also, I just realize you said you "will try to upgrade to the latest stable version". Our [latest release](https://github.com/Microsoft/msphpsql/releases/tag/v5.2.0-RC) is already a release candidate and it is very close to the stable version we will release in the near future. I would really appreciate it if you can try the release candidate out.

Thank you.

**Comment by rapemer** [comment]
@v-kaywon 
we upgraded to the latest release (5.2.0-RC) and the bug is resolved. Many thanks for your help, I'm closing this issue :+1:
