### ISSUE TITLE
Dual procedural and object-oriented interface

### ISSUE THREAD

**Issue by sirio3mil** [Microsoft/msphpsql#67]
Please try to implement this feature for one of nexts releases it is helpful. Such as other drives it would be nice have a class named sqlsrv.

**Comment by meet-bhagdev** [comment]
Hello @sirio3mil can you please shed some more light on what is your feature request is here? Some more details around the scenarios and use case will help! 

Cheers,
Meet

**Comment by sirio3mil** [comment]
Hi @meet-bhagdev what I mean is the option to have not only f.e. sqlsrv_query but its version in OOP, just like mysqli.

For example, Mysqli have mysqli_query in a procedural way but have mysqli::query in an OOP enviroment.

Cheers

**Comment by dhazelett** [comment]
@sirio3mil This driver provides the `sqlsrv_*` functions. As far as a `SqlSrv` class goes that's just a waste of time since they are developing a PDO driver as well.

You can do like [`doctrine/dbal`](https://github.com/doctrine/dbal), and create your own [wrapper](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php) for specific database engines though.


```php
class SqlSrv extends SomeBaseClass
{
    public function __construct($dsnOrPdo = null)
    {
        $this->connect($dsnOrPdo);
        // ....
    }
}
```

**Comment by sirio3mil** [comment]
Hi @dhazelett thanks for your comment but thats exactly what I have and thats why this is a request for new feature.

Regards.

**Comment by David-Engel** [comment]
We have no plans to develop another interface for this driver. Closing this issue.
