### ISSUE TITLE
SQLSTATE[08001] SQLDriverConnect: 10054 [unixODBC][Microsoft][ODBC Driver 11 for SQL Server]TCP Provider: Error code 0x2746 (with PDO_ODBC)

### ISSUE THREAD

**Issue by choplan** [Microsoft/msphpsql#681]
+## Driver version or file name
 Using PDO_ODBC
 +## SQL Server version
 2016
 +## Client operating system
RedHat 6.8
 +## PHP version
5.6.30
 +## Microsoft ODBC Driver version
libmsodbcsql-13.1.so.9.2 or libmsodbcsql-11.0.so.2270.0
 +## Table schema
 N/A
 +## Problem description
I am getting : 
SQLSTATE[08001] SQLDriverConnect: 10054 [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x2746
SQLSTATE[08001] SQLDriverConnect: 10054 [unixODBC][Microsoft][ODBC Driver 11 for SQL Server]TCP Provider: Error code 0x2746
NB : PHP program cannot connect via apache module. But program works when run using the php binary.
Via the web url, getting the error below. When running php test.php, it successfully connects.
 +## Expected behavior and actual behavior
Program should connect via apache module. I am not sure what I am missing.
 +## Repro code
 $dbh = new PDO("odbc:Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0;Server=machine1,12345;Database=master;","$username","$password");
 $dbh = new PDO("odbc:Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-libmsodbcsql-13.1.so.9.2;Server=machine1,12345;Database=master;","$username","$password");

**Comment by david-puglielli** [comment]
@choplan We do not support pdo_odbc, so we cannot help if the problem is caused by that extension. However, if your script runs fine from the command line and only fails when connecting to the apache module,  you may need to edit the apache configuration files (apache may have its own php.ini file, which is separate from the one used by the PHP binary). 

Also, I notice that in your connection string, you have set port 12345. Just to clarify, the default port for SQL Server is 1433.

**Comment by choplan** [comment]
Hi David
Thks for your quick reply.
As a matter of fact, found out that the apache mod_ssl had been statically compiled wih OpenSSL 0.9.8 and that lib does not work the recent TLS 1.2 implementation, causing some issues on servers enforcing this.
So nothing to see with the linux mssql odbc driver. If I may, one great stuff to add would be the support of the dynamic ports.
thk you
