### ISSUE TITLE
Can't get past missing ODBC errors

### ISSUE THREAD

**Issue by elramus** [Microsoft/msphpsql#689]
Hi there, I've been following the instructions here very carefully and done this multiple times now on a fresh VM images of Ubuntu, starting totally empty (followed instructions for Ubuntu 16.04, PHP 7.1). Can't seem to get PHP talking to ODBC properly! Any help would be much appreciated!

Following the instructions is straightforward, and the only snag I hit is when using pecl. I get:
`Warning: Invalid argument supplied for foreach() in PEAR/Command.php on line 249` a bunch of times over. `apt-get php-xml ` solves this, and after that it goes fine. Used the regular, stable version of pecl.

Next I restart apache, and finally the VM box for good measure. At this point, `php -v` gives me:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20170718/pdo_sqlsrv.so (/usr/lib/php/20170718/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_sqlsrv.so.so (/usr/lib/php/20170718/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20170718/sqlsrv.so (/usr/lib/php/20170718/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/sqlsrv.so.so (/usr/lib/php/20170718/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

I'm not sure where the `.so.so` came from, tried this multiple times on clean VM images and got that same thing. `php -v` is also telling me I’m on v 7.2, which is curious to me because everything in the installation is 7.1. 

But anyway, phpinfo in the browser does says 7.1, and it also tells me that sqlsrv is enabled, and that it’s version 4.3. `php -m` also lists sqlsrv and pdo_sqlsrv. I can also confirm ODBC with odbcinst -j, which tells me:
```
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/vagrant/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

So that looks pretty good, right? But when I go to actually use sqlsrv PDO, I get:
```
PDOException: SQLSTATE[IMSSP]: This extension requires the Microsoft ODBC Driver 13 for SQL Server to communicate with SQL Server. Access the following URL to download the ODBC Driver 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 in /var/www/html/Xenial/connect_pdo.php:10 Stack trace: #0 /var/www/html/Xenial/connect_pdo.php(10): PDO->__construct('sqlsrv:server=1...', 'LukeR', 'Reset123') #1 {main}
```
And if I use sqlsrv_connect, I get: 
```
Array ( [0] => Array ( [0] => IMSSP [SQLSTATE] => IMSSP [1] => -49 [code] => -49 [2] => This extension requires the Microsoft ODBC Driver 11 or 13 for SQL Server. Access the following URL to download the ODBC Driver 11 or 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 [message] => This extension requires the Microsoft ODBC Driver 11 or 13 for SQL Server. Access the following URL to download the ODBC Driver 11 or 13 for SQL Server for x64: http://go.microsoft.com/fwlink/?LinkId=163712 ) [1] => Array ( [0] => IM002 [SQLSTATE] => IM002 [1] => 0 [code] => 0 [2] => [unixODBC][Driver Manager]Data source name not found, and no default driver specified [message] => [unixODBC][Driver Manager]Data source name not found, and no default driver specified ) ) 
```
The code for testing out these connections comes from here, outlining `sqlsrv_connect` and `new PDO`. 
https://docs.microsoft.com/en-us/sql/connect/php/how-to-connect-using-sql-server-authentication

One last thing: I can successfully use `sqlcmd` to query the database and retrieve rows of actual data. So it’s not a firewall issue or anything on the DB end as far as I can tell. 

Any ideas? Thank you!

**Comment by david-puglielli** [comment]
@elramus One thing that sometimes seems to happen when installing PHP by package is that `php-pear` installs the most recent php 7.2 configuration files. This can happen if you are installing `php-pear` at the same time as `php7.1` and/or `php7.1-dev`, resulting in two sets of configuration files, which of course can cause trouble. In particular, it's clear that the PDO_SQLSRV driver loads for you, otherwise you would not get a message saying `This extension requires the Microsoft ODBC Driver ...` even though you are getting an error about another pdo_sqlsrv.so. And if you look at the full path to that extension in the error message, the 20170718 is a php 7.2 datestamp. So your installation is looking for pdo_sqlsrv in two places, but can't find it in one place (the php 7.2 extension directory), and it's the other one that is giving you the error.

So I suggest trying `apt-get install php7.1 php7.1-dev php7.1-xml`. The correct version of `php-pear` will then be installed as a dependency. This should solve the first problem and ensure you are using only php 7.1. 

As to the error `This extension requires the Microsoft ODBC Driver 13 for SQL Server...`, this can happen if your ODBC driver is version 17. The stable pdo_sqlsrv release, which is what gets installed when you run `pecl install pdo_sqlsrv`, is version 4.3.0, which does not support ODBC 17 - it will look for ODBC 11 or 13 and complain if it can't find it. If you ran `apt-get install msodbcsql`, you installed ODBC 17, which has been pushed to the repositories just last week. Therefore, I suggest installing a more recent preview version of the pdo_sqlsrv driver which supports ODBC 17 using `pecl install pdo_sqlsrv-5.2.0RC1` (and similarly for sqlsrv). 

These steps should solve your problems, please let us know how it goes. Apologies for the flaws in the documentation, as we are in the process of updating it for the pending stable release of the php drivers, but it will not be updated until that release goes into general availability.

**Comment by parite** [comment]
Using Ubuntu 16.04 and PHP7.0 using sqlsrv 4.0.8 production drivers, had the same issue after running `apt-get upgrade`. Reverted back to ODBC 13 with:

`sudo apt-get install msodbcsql=13.1.9.2-1`

**Comment by elramus** [comment]
@david-puglielli you're the stuff of legends! Everything is working now, thank you!!

**Comment by diblack** [comment]
I install on deb 9, I have the same error, I fix it run:
`pecl install sqlsrv
pecl install pdo_sqlsrv`
then, restart apache. Be sure that you run it, maybe you skip that step.
