### ISSUE TITLE
TVP support? [feature request]

### ISSUE THREAD

**Issue by xmlapi** [microsoft/msphpsql#795]
are there are plans of supporting table valued parameters? (example: passing several rows to a stored procedure)

**Comment by srutzky** [comment]
Hello @David-Engel (and @xmlapi and others): TVPs were introduced in SQL Server **2008**!! TVPs are an incredibly powerful feature that allows for increasing scalability. That only makes SQL Server a more attractive (and competitive) option. It boggles my mind that this is not a major priority. I'm still amazed that it took until January of **2017**, with the release of version 6.0, for the [JDBC SQL Server driver to finally support TVPs](https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver#60). I'm not sure what factors you look at to determine priorities, but I certainly hope the number of up-votes here is not a major factor given that it's but a fraction of reality. How many people even know about this repo? How many of those people don't vote because they don't have a GitHub login and don't care to get one just to upvote one issue? How many people never even look for something like this? How many people just don't ask for this because they aren't looking for it because they don't even know what TVPs are? Clearly there was enough demand to get TVP support added to the JDBC driver, right? While that might not be the exact same audience, I can't imagine that there isn't enough overlap between the Java and PHP communities to simply infer a similar level of interest.

TVPs are clearly supported by ODBC (which is the underlying transport used by this driver), so please add support for them to the PHP SQL Server driver:

* [Table-Valued Parameters (ODBC)](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-table-valued-parameters/table-valued-parameters-odbc)
* [Use Table-Valued Parameters (ODBC)](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-how-to/use-table-valued-parameters-odbc)

Thanks!  😺 


Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by David-Engel** [comment]
@srutzky TVPs are definitely high on the feature priority list for PHP. Unfortunately, I don't have a timeline I can share for it. Thanks for the feedback, though. It really does help make a difference.

Regards,
David

**Comment by yitam** [comment]
Closing this issue as per [5.10.0-beta1](
https://github.com/microsoft/msphpsql/releases/tag/v5.10.0-beta1)
