### ISSUE TITLE
5.6.0 missing on PECL

### ISSUE THREAD

**Issue by remicollet** [Microsoft/msphpsql#928]
https://github.com/Microsoft/msphpsql/releases/tag/v5.6.0 is tagged, but not available in PECL (still at 5.3.0/stable and 5.5.0preview/devel)

**Comment by david-puglielli** [comment]
We are preparing for the next release, which is expected to happen within the next week, but first we need to wait for the ODBC driver release, which is expected in the next few days. The tag is there because it's necessary for some of our testing, but does not necessarily mean the release is ready.

**Comment by david-puglielli** [comment]
5.6.0 is now released! Closing this issue.
